% TODO: Test function r_ltp = gei2ltp(r_gei, sensor, dNm)
% TODO: Test function CIRS = TETEDToCIRS(mjd, TETED)
% TODO: Test function TIRS = CIRSToTIRS(mjd, CIRS)
% TODO: Test function SEZ = ITRSToSEZ(ITRS, ITRS_0, geodetic_latitude, longitude)
% TODO: Test function ITRS = SEZToITRS(SEZ, ITRS_0, geodetic_latitude, longitude)
% TODO: Test function CIRS = TIRSToCIRS(mjd, TIRS)
% TODO: Test function TETED = CIRSToTETED(mjd, CIRS)
% TODO: Test function r_gei = ltp2gei(r_ltp, sensor, dNm)
